"""Domain models representing resume data."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List


@dataclass(frozen=True)
class ResumeChunk:
    """Represents a piece of resume content used for retrieval."""

    chunk_id: str
    text: str
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class ResumeDocument:
    """Normalized resume representation after OCR."""

    resume_id: str
    filename: str
    content_type: str
    language: str
    extracted_text: str
    chunks: List[ResumeChunk]
    created_at: datetime


@dataclass(frozen=True)
class ResumeSummary:
    """Summary generated by the LLM."""

    resume_id: str
    summary: str
    highlights: list[str]

